Build Youtube structure webpage based on requirements
aristides1000/basic-html-page-structure pull request #1
Opened 2020-09-18 17:53 UTC by carloso0114

We used HTML5 y CSS3 and assets forlder that cointains pictures and gif files, in order to make a good looking page.
Linters config file where added.

2020-09-18 23:09 UTC, teekaytech requested changes
# Status: Changes Required :recycle: :vertical_traffic_light: 

### Hi team :wave: 

**You guys have really done an awesome job so far: :clap:**
- You were able to set up GitHub Actions for this project, and that is so cool :100: 
- Proper attention is paid to the details of the webpage :+1: 
- Proper use of GitHub Flow :ok_hand: 

**Overall, the project is looking good, but you need to make a few adjustments to make your project great :muscle: Kindly review the highlighted points below :point_down: and make changes as appropriate.**

* * *

**[ REQUIRED CHANGES ]**

_These changes must be made before the project can be approved._

- [ ] You are required to add at least 3 images/icons to the rightmost part of your navbar.
- I understand that we have 2 icons in the template, kindly add one more icon to complete this requirement. You can visit the same section of the current youtube page for inspiration.

![n](https://user-images.githubusercontent.com/26856491/93651360-2031b680-fa09-11ea-8160-f68b8670dd71.png)

- [ ] Your page is having a horizontal scroll bar. This is not respected. Kindly check which of the containers' width is bringing about the scroll bar and adjust it so that your page does not scroll horizontally. 

![bar](https://user-images.githubusercontent.com/26856491/93651527-abab4780-fa09-11ea-9c79-9dd609a5159f.png)

- [ ] Please check my comments in the in-line section below and make the changes.
- Fix all issues related to your readme

* * * 

**[ OPTIONAL CHANGES ]**

_These changes are not compulsory: your project will be approved without implementing them. However, making these changes makes you a better developer and makes your project presentable._

- [ ] Be consistent with your CSS selectors. [Check out this page](https://speckyboy.com/good-bad-css-practices) for best CSS practices
- It is better you use elements' class names for their CSS rules. Using Id for styling can be costly at times because Id has higher precedence over classes. Therefore, using the two interchangeably may introduce some bugs in the nearest future.

- [ ] You are encouraged to implement the comments section of this page.

![a](https://user-images.githubusercontent.com/26856491/93651871-ea8dcd00-fa0a-11ea-95a1-b8b99d130601.png)

- [ ] You should try to use HTML5 semantic tags, such as `<main>`, `<section>`, `<footer>` tags in your project. [This link](https://www.w3schools.com/html/html5_semantic_elements.asp) should get you started with semantic HTML

**[ COMMENTS ]**
- Against your next project, please let your commit messages be more descriptive and be consistent with it.
- Do not give up: you are almost there. 

### Kindly make the required changes and submit another code review request form.

You can also reach out to me on slack (@taofeekolalere) if you need further clarification.

Happy coding :man_technologist:

2020-09-18 23:09 UTC, teekaytech commented on README.md
> +- HTML5
Use bullet for git too, as you've done for the other technologies listed.

2020-09-18 23:09 UTC, teekaytech commented on README.md
> +- LinkedIn: [LinkedIn](https://www.linkedin.com/in/carlos-ospina-242b831a6/)
Put your handles directly inside the square brackets, followed by the URL. e.g.
`GitHub: [@carloso0114](https://github.com/carloso0114)`

2020-09-18 23:09 UTC, teekaytech commented on index.html
> +    <a href="about:blank"> <img src="assets/youtube_icon.png" alt="youtube-icon" height="80" id="youtube-icon"></a>
The `alt` attribute is missing on your `<img>` tags. Always use the `alt` attribute as it provides an alternate text should in case the image is not loading or not found.

2020-09-18 23:09 UTC, teekaytech commented on index.html
> +  </header>
Your `<header>` tag is empty. The best practice is to put the `<header>` tag inside your `<nav>` tag. i.e.
```
<nav>
<header>
--- header contents ---
</header>
</nav>
```

Please fix this.

2020-09-18 23:09 UTC, teekaytech commented on index.html
> +      <img src="assets/uploadbtn.png" alt="a" height="50" id="upload-icon">
Although the `<alt>` attribute is specified here, it still does not do the job because the value you used (which is 'a') is not meaningful. Please use a meaningful value for the `<alt>` attribute.

2020-09-18 23:09 UTC, teekaytech commented on README.md
>  ## Getting Started
Sections `Getting Started, Prerequisites, Setup, Install, Usage, Run tests, and Deployment` should be modified to match your project. Also, remove the sections that do not apply to your current project.

2020-09-21 15:25 UTC, carloso0114 commented on index.html
> +  </header>
In the webpage we got this info.
![image](https://user-images.githubusercontent.com/14119855/93785425-b1fd1780-fbf3-11ea-9a67-4391eb051981.png)
Acording to [https://stackoverflow.com/questions/51609208/html5-page-structure-section-and-article-correct-placement](url)
![image](https://user-images.githubusercontent.com/14119855/93785925-48c9d400-fbf4-11ea-85b4-f6d98bcb2332.png)
We kindly take your advice, however we wanted to ask if this information is realiable.

2020-09-21 16:54 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED ♻️ 

Team, very good job implementing the required changes! 💪 
I can see you have been working hard on this project 👍 
Keep it up!

However, there are still some changes you need in order to get this project approved. 
Check my comments below 👇 , apply the changes and request for a new code review when they are done to move forward ⏩ 

- Please, change the id's into classes, since it is  a better practice, classes can be reusable, take profit of it! 💪 

[OPTIONAL]
- You can add more meaningful HTML tags, you can use different ones than `div`, try to use `section`, `main` or `aside` tags, it will make your code cleaner and more readable


Good luck guys 😃

2020-09-21 16:54 UTC, javitocor commented on README.md
> +git
Please, add a bullet point to 'git'.

2020-09-21 16:54 UTC, javitocor commented on README.md
> +Google - For letting us find crucial information in order to create this project
Add one line for each acknowledge

2020-09-21 16:54 UTC, javitocor commented on index.html
> +      <a href="about:blank"> <img src="assets/youtube_icon.png" alt="youtube-icon" height="80" id="youtube-icon"></a>
Kindly remove inline styling, it is not a good practice and we should avoid it. Please, use classes to style the different HTML tags.

2020-09-21 16:54 UTC, javitocor commented on index.html
> +        <img src="assets/perfil-pic.jpg" alt="perfil-pic" height="50" class="perfil-pic">
Same here, avoid inline styling.

2020-09-21 16:54 UTC, javitocor commented on index.html
> +      <a href="#" class="right-elements text-color-white" style="text-decoration: none;">
Same here...

2020-09-21 16:54 UTC, javitocor commented on index.html
> +              <img src="assets/profile-pic.jpg" alt="profile-pic" style="width: 130%;">
same here...

2020-09-21 16:54 UTC, javitocor commented on index.html
> +          <div style="font-weight: bold; padding: 1rem;">
same here...

2020-09-21 16:54 UTC, javitocor commented on index.html
> +          <a href="#" style="text-decoration: none; color: black;">
same here...

2020-09-21 16:54 UTC, javitocor commented on index.html
> +            <img src="assets/loading-icon.gif" alt="loading-icon" width="20" height="20">
same here

2020-09-21 19:44 UTC, blackpintz approved these changes
# Status: Project Approved.
 ## Hi team,
**Congratulations on your project.😃**
# Optional

1).   **Here are some tips for the readme section:**

-  **Ensure the screenshot is displaying properly.**

- **Instead of using @githubhandle, @twitterhandle, you can provide a link on your username instead, e.g Github: @carloso0114.**

## Good luck on your next project!

## PS: If you want to reach out, send me a message on slack (@Rose Wanjohi)

2020-09-21 20:17 UTC, merged